server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false

plugins:
  youtube:
    enabled: true
    clients:
      - WEB
      - ANDROID
      - WEB_EMBEDDED_PLAYER
      - MUSIC

logging:
  level:
    root: WARN
